### ISSUE TITLE
Support 8.1

### ISSUE THREAD

**Issue by pixietrixibell** [andrew-svirin/eusphpe-php#10]
Hi, 
is it possible to create a library for linux also for php 8.1?
@denpavl @andrew-svirin @nosovk

**Comment by andrew-svirin** [comment]
Hi @pixietrixibell of course.

**Comment by nosovk** [comment]
actually it seems that iit removed link to binaries. Cant find new version now :(

**Comment by pixietrixibell** [comment]
Someone send me this link: https://iit.com.ua/download/EUSPHPE-20210621.zip
I think there si version for 8.1.4 ( eusphpei.64.8.1.4.ts.tar )  :)

**Comment by nosovk** [comment]
this is link from this repo :)

**Comment by pixietrixibell** [comment]
> 

I just noticed that. :face_with_spiral_eyes:  Sorry about that, my big failure.

**Comment by nosovk** [comment]
actually it's very strange that they updated contents of an existing archive. But anyway I added PR with current version, and PHP 8.1 is there.
