### ISSUE TITLE
Unable to load dynamic library's

### ISSUE THREAD

**Issue by ZhmerenkaSolution** [andrew-svirin/eusphpe-php#12]
After installation according to instruction (for Fedora as closest) from EUSignPHPDescription.doc

On CentOs 7.9
php-fpm 5.6

`php-fpm` log file:
`[30-Jan-2023 06:38:34 UTC] PHP Warning:  PHP Startup: eusphpe: Unable to initialize module
Module compiled with build ID=API20131226,NTS
PHP    compiled with build ID=API20131226,TS
These options need to match
 in Unknown on line 0`

And for all other IIT library's:
`[30-Jan-2023 06:38:34 UTC] PHP Warning:  PHP Startup: Invalid library (maybe not a PHP library) '/usr/lib/php56/eusphpe_extension/cac.so' in Unknown on line 0`

I saw that `PHP compiled with ,TS` and I tried to use .ts version, but faced the same error as here #7
`PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php56/eusphpe_extension/eusphpe.so' - /usr/lib/php56/eusphpe_extension/eusphpe.so: undefined symbol: ts_allocate_id in Unknown on line 0`

More over, `php-fpm -m` outputs `eusphpe` module, but in runtime throws errors `Fatal error: Call to undefined function euspe_init()` and on any other euspe functions.

Any ideas how to fix this?

**Comment by andrew-svirin** [comment]
@ZhmerenkaSolution which archive did you use? https://github.com/andrew-svirin/eusphpe-php/tree/master/docs/EUSPHPE/Modules

**Comment by ZhmerenkaSolution** [comment]
@andrew-svirin eusphpei.64.5.6.9.tar
I actually realized that I used wrong architecture library's (x86_64 = 32), but now I see another error on all library's:
`PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php56/eusphpe_extension/eusphpe.so' - /usr/lib/php56/eusphpe_extension/eusphpe.so: wrong ELF class: ELFCLASS32 in Unknown on line 0`

**Comment by andrew-svirin** [comment]
@ZhmerenkaSolution did you add to loaded so-packages into PHP?

**Comment by ZhmerenkaSolution** [comment]
@andrew-svirin yes, in /usr/lib/php56/eusphpe_extension/ .so files and in /etc/php-zts.d eusphpe.ini where in file `extension="/usr/lib/php56/eusphpe_extension/eusphpe.so"`.

**Comment by andrew-svirin** [comment]
@ZhmerenkaSolution  print list of loaded extensions. PHP-FPM probably need to be restarted.

**Comment by ZhmerenkaSolution** [comment]
@andrew-svirin 
![123](https://user-images.githubusercontent.com/69646713/215511521-811da284-cb76-4422-a92c-1b29373afaef.png)
As you can see eusphpe in the list, but I still get error `Fatal error: Call to undefined function euspe_init()`.
And I always reload php-fpm and apache after changes.

**Comment by andrew-svirin** [comment]
Could you echo list of extensions immediately before `euspe_init` ? https://www.php.net/manual/en/function.get-loaded-extensions.php

**Comment by ZhmerenkaSolution** [comment]
@andrew-svirin 
There is no eusphpe:
Array ( [0] => Core [1] => date [2] => ereg [3] => libxml [4] => openssl [5] => pcre [6] => zlib [7] => filter [8] => hash [9] => Reflection [10] => SPL [11] => session [12] => standard [13] => apache2handler [14] => bz2 [15] => calendar [16] => ctype [17] => curl [18] => dom [19] => mbstring [20] => fileinfo [21] => ftp [22] => gd [23] => gettext [24] => iconv [25] => intl [26] => exif [27] => mcrypt [28] => mysqlnd [29] => PDO [30] => Phar [31] => posix [32] => shmop [33] => SimpleXML [34] => soap [35] => sockets [36] => sqlite3 [37] => sysvmsg [38] => sysvsem [39] => sysvshm [40] => tokenizer [41] => xml [42] => xmlwriter [43] => xsl [44] => mysql [45] => mysqli [46] => pdo_mysql [47] => pdo_sqlite [48] => wddx [49] => xmlreader [50] => xmlrpc [51] => zip [52] => json [53] => mhash [54] => Zend OPcache ) 

I looked in internet about `wrong ELF class: ELFCLASS32` and it seems like I need return back x64 library's. PHP log still throw this `PHP Warning:  PHP Startup: eusphpe: Unable to initialize module
Module compiled with build ID=API20131226,NTS
PHP    compiled with build ID=API20131226,TS
These options need to match`.

**Comment by andrew-svirin** [comment]
You see that PHP CLI has loaded `eusphpe` and PHP FPM have not. How it is possible?

**Comment by ZhmerenkaSolution** [comment]
@andrew-svirin I don't know, seems like PHP CLI read .ini file with extensions from `/etc/php.d/` and PHP FPM from `/etc/php-zts.d` (which also prints phpinfo), but PHP FPM unable to initialize library. Leaving extensions only in `/etc/php-zts.d` nothing changes (just `php-fpm -m` doesn't print it anymore).
Any ideas what should I do?

**Comment by andrew-svirin** [comment]
More of that. You can have absolutely different PHP versions for ether CLI and FPM. Find in `phpinfo()` where from is loading config and setup for each PHP `eusphpe` of version you need.

**Comment by ZhmerenkaSolution** [comment]
@andrew-svirin I've finally loaded this, many thanks, as you suggested I was confused by different CLI and FPM versions. `phpinfo()` outputs `Thread Safety | enabled`, and I used TS version which is works.
