### ISSUE TITLE
EU_ERROR_LIBRARY_LOAD

### ISSUE THREAD

**Issue by ZhmerenkaSolution** [andrew-svirin/eusphpe-php#14]
Hi again.
I'm installing your library to new environment (CentOs 9, php8.0/8.1). PHP module loaded as well, but on `euspe_init()` library throws `0x0003 EU_ERROR_LIBRARY_LOAD`. I know it's euspe library error - not eusphpe, but maybe you have any idea what can cause it?

**Comment by andrew-svirin** [comment]
I recommend to check setup.

![image](https://user-images.githubusercontent.com/16819743/219067482-d631995f-bc5e-4bc4-8398-5bab8038f444.png)

**Comment by ZhmerenkaSolution** [comment]
@andrew-svirin yea, I already copied from it to you, but it's not really informative...

**Comment by andrew-svirin** [comment]
Then I do not know.
