### ISSUE TITLE
Libraries versions (eusphpe, etc.)

### ISSUE THREAD

**Issue by denpavl** [andrew-svirin/eusphpe-php#3]
Hello!

I'm using `eusphpe.so` library functions, but have issue - last version is for PHP 7.2.2.

Maybe you know how can I receive this library for PHP 7.3 (7.4) ?

Thanks!

https://github.com/andrew-svirin/eusphpe-php/blob/26ecddf8be766218c1eb566cb1f12eaec86a105c/docs/EUSPHPE-20180505/Modules/Linux/64/eusphpei.64.7.2.2.tar

**Comment by andrew-svirin** [comment]
Hello @denpavl Unfortunately i have not such lib. And have switched on php 7.2 for this.
As i know this project going to be Browser oriented and be written on JS. So eusphpe for PHP looks like depricated and not perspective.

**Comment by denpavl** [comment]
@andrew-svirin thanks for answer!

Finally we got answer with updated libs.
I created MR https://github.com/andrew-svirin/eusphpe-php/pull/4

**Comment by andrew-svirin** [comment]
Great! Merged.
