### ISSUE TITLE
user-name settings

### ISSUE THREAD

**Issue by iceprox** [andrew-svirin/eusphpe-php#8]
user-name must be == cert file name or?

**Comment by iceprox** [comment]
or can you please review example for User settings ? becouse i get this error : RuntimeException: Check the correctness of functions invokation order.

**Comment by andrew-svirin** [comment]
One of the reason of this error is ACSK server server error.
But follow example and all will work.
Also you can check this way https://github.com/andrew-svirin/eusphpe-php/blob/master/tests/Unit/ClientTest.php
